# 工作流名称
name: EDK2 Build

# 触发条件，这里示例为当推送到main分支时触发
on:
  push:
    branches:
      - main

# 权限设置
permissions:
  contents: read
  id - token: write

# 作业定义
jobs:
  build - and - upload:
    # 运行在最新的Ubuntu系统上
    runs - on: ubuntu - latest

    steps:
      # 检出代码仓库
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 这里可以添加构建EDK2项目的步骤，例如安装依赖、执行构建脚本等
      - name: Install Dependencies
        run: |
          # 安装必要的软件包
          sudo apt - get update
          sudo apt - get install - y some - required - package

      - name: Build EDK2
        run: |
          # 进入项目目录并执行构建命令
          cd edk2
          ./build - script.sh

      # 上传构建产物
      - name: Upload artifacts
        uses: actions/upload - artifact@v4
        with:
          name: OVMF - Firmware
          path: |
            edk2/Build/OvmfX64/RELEASE_GCC5/FV/OVMF_CODE.fd
            edk2/Build/OvmfX64/RELEASE_GCC5/FV/OVMF_VARS.fd
          retention - days: 7
